# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_backend', '0003_auto_20161217_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
